name: Teacher_Program
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.0.0
  cupertino_icons: ^1.0.0
  responsive_builder:
  font_awesome_flutter: ^10.5.0
  google_fonts: ^4.0.3
  flutter_rounded_progress_bar:
  url_launcher: ^6.0.20
  url_launcher_web:
  characters:
  get_it: ^7.6.0
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  cloud_firestore:
  file_picker: ^8.1.7
  shared_preferences:
  flutter_bloc:
  cached_network_image:
  equatable:
  appinio_video_player: ^1.2.2
  video_player: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Agustina
      fonts:
        - asset: assets/fonts/Agustina.ttf
