// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJzjzO819YpG3Qo2XlyqzIhjZFt8y9C-Q',
    appId: '1:970628937309:web:9b07bbd38aca6fc6d5bfb4',
    messagingSenderId: '970628937309',
    projectId: 'emothions-6e185',
    authDomain: 'emothions-6e185.firebaseapp.com',
    storageBucket: 'emothions-6e185.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-1pTXCpQN21YY3M_BQakI7n3O0b9hi0',
    appId: '1:970628937309:android:915b56f0bec8fca6d5bfb4',
    messagingSenderId: '970628937309',
    projectId: 'emothions-6e185',
    storageBucket: 'emothions-6e185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA5Hsfp2Hn3NLRwHUpcg_bsLd4Yn_j-0Y',
    appId: '1:970628937309:ios:b081e5c0854a22d8d5bfb4',
    messagingSenderId: '970628937309',
    projectId: 'emothions-6e185',
    storageBucket: 'emothions-6e185.appspot.com',
    iosBundleId: 'com.example.DeveloperFolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJzjzO819YpG3Qo2XlyqzIhjZFt8y9C-Q',
    appId: '1:970628937309:web:4c8bffdd39cb1c2fd5bfb4',
    messagingSenderId: '970628937309',
    projectId: 'emothions-6e185',
    authDomain: 'emothions-6e185.firebaseapp.com',
    storageBucket: 'emothions-6e185.appspot.com',
  );
}
